add_newline = false
# A minimal left prompt
format = """$directory$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right - selective modules only
right_format = """$git_branch$git_status$nodejs$python$golang$aws$kubernetes$time$status"""
command_timeout = 1000

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[➜](bold green)'

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = " "

[golang]
format = '[ ](bold cyan)'

[kubernetes]
symbol = '☸ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "omerxx", symbol = " " },
]

[docker_context]
disabled = true

[python]
# Disable showing virtual environment names and Python project info
disabled = false
format = 'via [🐍 $version]($style) '
# Don't show virtual environment name
python_binary = ['python', 'python3', 'python2']
detect_extensions = ['py']
detect_files = ['requirements.txt', '.python-version', 'pyproject.toml', 'Pipfile', 'tox.ini', 'setup.py', '__init__.py']
detect_folders = []

[package]
# Disable showing package names from package.json, etc.
disabled = true

[conda]
# Disable conda environment display
disabled = true

[nodejs]
# Only show Node version, not project names
format = 'via [ $version]($style) '
detect_extensions = ['js', 'mjs', 'cjs', 'ts', 'tsx']
detect_files = ['package.json', '.node-version', '.nvmrc']
detect_folders = ['node_modules']

[env_var.MISE_ENV]
# Disable mise environment display completely
disabled = true

[custom.mise]
# Disable any custom mise prompt integration
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
